import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

// —— 构建 styles.css：把 src/styles/*.css 拼成根目录 styles.css ——
// 顺序：base.css 在前（含 :root 变量、组件样式），prism.css 在后（代码块高亮兜底）
// production：额外调用 esbuild 的 CSS minifier，可省约 25% 体积
const isProd = process.argv[2] === "production";
async function bundleStyles() {
  const dir = path.resolve("src/styles");
  const order = ["base.css", "prism.css"];
  const parts = order
    .filter((f) => fs.existsSync(path.join(dir, f)))
    .map((f) => `/* ==== ${f} ==== */\n` + fs.readFileSync(path.join(dir, f), "utf8"));
  const merged = parts.join("\n\n");
  const header = isProd
    ? `/* AUTO-GENERATED — production build (minified). Source: src/styles/{base,prism}.css */\n`
    : `/* AUTO-GENERATED by esbuild.config.mjs — do NOT edit directly.\n   Source: src/styles/{base,prism}.css */\n\n`;
  let out = merged;
  if (isProd) {
    const res = await esbuild.transform(merged, { loader: "css", minify: true });
    out = res.code;
  }
  fs.writeFileSync("styles.css", header + out, "utf8");
  console.log(`[styles] bundled ${parts.length} files → styles.css (${(fs.statSync("styles.css").size/1024).toFixed(1)} KB${isProd ? ", minified" : ""})`);
}
await bundleStyles();

// dev 模式下监听 src/styles 变化
if (!isProd) {
  try {
    fs.watch(path.resolve("src/styles"), { persistent: true }, () => { void bundleStyles(); });
  } catch { /* ignore */ }
}

const prod = isProd;

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  metafile: prod,
});

if (prod) {
  const result = await context.rebuild();
  if (result.metafile) {
    fs.writeFileSync("metafile.json", JSON.stringify(result.metafile, null, 2), "utf8");
    // 简要 top-10 报告到终端
    const inputs = Object.entries(result.metafile.inputs)
      .map(([p, m]) => ({ p, b: m.bytes }))
      .sort((a, b) => b.b - a.b)
      .slice(0, 10);
    console.log("[bundle] top-10 modules by source size:");
    for (const it of inputs) {
      console.log(`  ${(it.b/1024).toFixed(1).padStart(6)} KB  ${it.p}`);
    }
    const outBytes = fs.statSync("main.js").size;
    console.log(`[bundle] main.js = ${(outBytes/1024).toFixed(1)} KB (minified)`);
    console.log(`[bundle] full report: metafile.json  → analyze at https://esbuild.github.io/analyze/`);
  }
  process.exit(0);
} else {
  await context.watch();
}
